### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by piyushspss** [SciSharp/Numpy.NET#43]
How can I convert the below python line into NumSharp:
 `np.column_stack(np.where(mat > 0))`
 Thanks in advance.

**Comment by henon** [comment]
Thank you for pointing me to np.column_stack. It did misbehave if you passed only a single NDarray as parameter. This is fixed. Below you see a unit-test that shows that your code above indeed works now without any modification.

```c#
       [TestMethod]
        public void QuestionByPiyushspss()
        {
            // np.column_stack(np.where(mat > 0))

            //>>> a = np.array([1, 0, 0, 1, 2, 3, 0, 1]).reshape(2, 4)
            //         >>> a
            //array([[1, 0, 0, 1],
            //       [2, 3, 0, 1]])
            //>>> np.column_stack(a)
            //array([[1, 2],
            //       [0, 3],
            //       [0, 0],
            //       [1, 1]])
            //>>> np.where(a > 0)
            //(array([0, 0, 1, 1, 1], dtype = int64), array([0, 3, 0, 1, 3], dtype = int64))
            //>>> np.column_stack(np.where(a > 0))
            //array([[0, 0],
            //       [0, 3],
            //       [1, 0],
            //       [1, 1],
            //       [1, 3]], dtype = int64)
            //>>>
            var a = np.array(new[] {1, 0, 0, 1, 2, 3, 0, 1}).reshape(2, 4);
            var expected =
                "array([[1, 2],\n" +
                "       [0, 3],\n" +
                "       [0, 0],\n" +
                "       [1, 1]])";
            Assert.AreEqual(expected, np.column_stack(a).repr);
            Assert.AreEqual("(array([0, 0, 1, 1, 1], dtype=int64), array([0, 3, 0, 1, 3], dtype=int64))", np.where(a>0).repr);
            expected =
                "array([[0, 0],\n" +
                "       [0, 3],\n" +
                "       [1, 0],\n" +
                "       [1, 1],\n" +
                "       [1, 3]], dtype=int64)";
            Assert.AreEqual(expected, np.column_stack(np.where(a > 0)).repr);
        }
```

**Comment by henon** [comment]
released the fix as version 1.15 on nuget.

**Comment by piyushspss** [comment]
That's awesome. Thanks! :)

**Comment by piyushspss** [comment]
Hey @henon , when will this 1.15 version get released. I still see the version 1.14 as latest.

**Comment by henon** [comment]
I ran my release scripts, but obviously something went wrong. Looking at it now

**Comment by henon** [comment]
I hadn't updated my nuget key. They should be online any minute now

**Comment by henon** [comment]
@piyushspss: I found out that np.where doesn't behave right. when called without the optional parameters x and y it returns a tuple in python. Thus I have to change the return type for that case to NDarray[] in order to be able to work with that object. 

looks like this bug did not affect you, but I just want to let you know that I will change that in v18
